#!/bin/bash

# Authelia User Setup Script
# Creates initial admin user for Authelia

set -e

AUTHELIA_DIR="./authelia"
USER_FILE="$AUTHELIA_DIR/users_database.yml"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════╗"
echo "║        Authelia User Setup - ARR Stack            ║"
echo "╚═══════════════════════════════════════════════════╝"
echo -e "${NC}\n"

# Check if Docker is running
if ! docker ps &> /dev/null; then
    echo -e "${RED}✗ Docker is not running!${NC}"
    exit 1
fi

# Create authelia directory
mkdir -p "$AUTHELIA_DIR"

# Prompt for username
echo -e "${YELLOW}Enter username (default: admin):${NC}"
read -r USERNAME
USERNAME=${USERNAME:-admin}

# Prompt for password
echo -e "${YELLOW}Enter password:${NC}"
read -rs PASSWORD

if [ -z "$PASSWORD" ]; then
    echo -e "${RED}✗ Password cannot be empty!${NC}"
    exit 1
fi

# Generate password hash using Authelia's Docker image
echo -e "\n${YELLOW}Generating password hash...${NC}"
HASH=$(docker run --rm authelia/authelia:latest authelia crypto hash generate argon2 --password "$PASSWORD" | grep 'Digest:' | awk '{print $2}')

if [ -z "$HASH" ]; then
    echo -e "${RED}✗ Failed to generate password hash!${NC}"
    exit 1
fi

# Prompt for email
echo -e "${YELLOW}Enter email (optional):${NC}"
read -r EMAIL
EMAIL=${EMAIL:-user@arr.local}

# Create users_database.yml
cat > "$USER_FILE" << EOF
---
###############################################################
#                         Users Database                      #
###############################################################

users:
  $USERNAME:
    displayname: "$USERNAME"
    password: "$HASH"
    email: $EMAIL
    groups:
      - admins
      - users
EOF

echo -e "\n${GREEN}✓ User created successfully!${NC}\n"
echo -e "${BLUE}User Details:${NC}"
echo -e "  • Username: ${GREEN}$USERNAME${NC}"
echo -e "  • Email: ${GREEN}$EMAIL${NC}"
echo -e "  • Groups: ${GREEN}admins, users${NC}"

echo -e "\n${YELLOW}Note: Encryption keys (JWT_SECRET, SESSION_SECRET, STORAGE_ENCRYPTION_KEY)${NC}"
echo -e "${YELLOW}are automatically generated by quick_setup.sh and stored in .env file.${NC}"
echo -e "${YELLOW}No manual configuration needed!${NC}"

echo -e "\n${GREEN}Done! Start Docker Compose to use Authelia.${NC}\n"
